server:
  port: 8080
spring:
#  mysql数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/redstar?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.10.109
    database: 0 #redis索引（默认为0）
    port: 6379  #Redis服务器连接端口
    password: #redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（负数表示无限制）
        max-idle: 8 #连接池中的最大空闲连接
        max-wait: -1ms  #连接池最大阻塞等待时间（负数表示无限制）
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000ms #连接超时时间（毫秒）
  elasticsearch:
    rest:
      uris: 192.168.10.109:9200
#r redis配置
mybatis:
  mapper-locations:
    - classpath:dao/*.xml

#自定义redis key
redis:
  database: redstar
  key:
    authCode:
      prefix: "portal:authCode" #验证码前缀
      expire: 120 #验证码过期时间（秒）
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时
# 自定义jwt key
jwt:
  tokenHeader: Authorization  #JWT存储的请求头
  secret: mySecret #JWT加密解密使用的密钥
  expiration: 604800 #JWT的过期时间(60*60*24)
  claimsHead: 'Bearer ' #JWT负载中拿到开头

secure:
  ignored:
    ignoreUrls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/*.gif
      - /*.html
      - /**/*.html
      - /**/*.json
      - /**/*.woff2
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /member/authCode
      - /member/verifyAuthCode
      - /member/login
      - /member/register
#邮箱配置
mail:
  qq:
    authentication:
      username: 604793921@qq.com
      password: axalpxejckiubegf
    name: redstar

