server:
  port: 8080
spring:
#  mysql数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/redstar?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.10.107
    database: 0 #redis索引（默认为0）
    port: 6379  #Redis服务器连接端口
    password: #redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（负数表示无限制）
        max-idle: 8 #连接池中的最大空闲连接
        max-wait: -1ms  #连接池最大阻塞等待时间（负数表示无限制）
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000ms #连接超时时间（毫秒）
#r redis配置
mybatis:
  mapper-locations: -classpath:dao/*.xml

#自定义redis key
redis:
  key:
    authCode:
      prefix: "portal:authCode" #验证码前缀
      expire: 120 #验证码过期时间（秒）
